export interface LoanTypeDetail {
  id: string;
  name: string;
  description: string;
  minAmount: number;
  maxAmount: number;
  typicalTerm: string;
  bestFor: string[];
  requirements: string[];
  rates?: string;
  color: string;
}

export const mortgageTypes: LoanTypeDetail[] = [
  {
    id: 'conventional',
    name: 'Conventional Mortgage',
    description: 'Traditional loan not backed by government, ideal for borrowers with strong credit',
    minAmount: 50000,
    maxAmount: 3000000,
    typicalTerm: '15-30 years',
    rates: '6.5% - 7.5%',
    bestFor: [
      'Borrowers with 620+ credit score',
      'Down payment of 3-20%',
      'Competitive interest rates',
      'No upfront mortgage insurance (20%+ down)',
    ],
    requirements: ['Debt-to-income ratio below 43%', 'Stable employment history', 'Documented income'],
    color: '#1D9BF0',
  },
  {
    id: 'fha',
    name: 'FHA Loan',
    description: 'Government-insured loan with lower down payment and credit requirements',
    minAmount: 50000,
    maxAmount: 970800,
    typicalTerm: '15-30 years',
    rates: '6.0% - 7.0%',
    bestFor: [
      'First-time homebuyers',
      'Lower credit scores (580+)',
      'Down payment as low as 3.5%',
      'Flexible qualifying standards',
    ],
    requirements: ['Mortgage insurance required', 'Property must meet FHA standards', 'Owner-occupied only'],
    color: '#00D66F',
  },
  {
    id: 'va',
    name: 'VA Loan',
    description: 'Zero down payment loan for eligible veterans, active military, and spouses',
    minAmount: 50000,
    maxAmount: 3000000,
    typicalTerm: '15-30 years',
    rates: '6.0% - 7.0%',
    bestFor: [
      'Veterans and active military',
      'No down payment required',
      'No private mortgage insurance',
      'Competitive interest rates',
    ],
    requirements: ['Certificate of Eligibility', 'Meet service requirements', 'VA funding fee (waived for disabled)'],
    color: '#F4212E',
  },
  {
    id: 'usda',
    name: 'USDA Loan',
    description: 'Zero down payment for rural and suburban homebuyers with moderate income',
    minAmount: 50000,
    maxAmount: 1000000,
    typicalTerm: '30 years',
    rates: '5.5% - 6.5%',
    bestFor: [
      'Rural and suburban properties',
      'No down payment required',
      'Low mortgage insurance',
      'Income limits apply',
    ],
    requirements: ['Property in USDA-eligible area', 'Income below area limits', 'Primary residence only'],
    color: '#00B85D',
  },
  {
    id: 'jumbo',
    name: 'Jumbo Loan',
    description: 'High-value mortgage exceeding conforming loan limits for luxury properties',
    minAmount: 766550,
    maxAmount: 10000000,
    typicalTerm: '15-30 years',
    rates: '7.0% - 8.0%',
    bestFor: [
      'High-value properties',
      'Excellent credit (700+)',
      'Larger down payments (10-20%)',
      'Higher income requirements',
    ],
    requirements: ['Significant cash reserves', 'Low debt-to-income ratio', 'Extensive documentation'],
    color: '#9E5AF2',
  },
  {
    id: 'fixed-rate',
    name: 'Fixed-Rate Mortgage',
    description: 'Interest rate stays the same for the entire loan term, predictable payments',
    minAmount: 50000,
    maxAmount: 3000000,
    typicalTerm: '10-30 years',
    rates: '6.5% - 7.5%',
    bestFor: [
      'Long-term homeowners',
      'Budget predictability',
      'Protection from rate increases',
      'Refinancing opportunities',
    ],
    requirements: ['Standard mortgage requirements', 'Varies by loan type'],
    color: '#1D9BF0',
  },
  {
    id: 'adjustable-rate',
    name: 'Adjustable-Rate Mortgage (ARM)',
    description: 'Lower initial rate that adjusts periodically based on market conditions',
    minAmount: 50000,
    maxAmount: 3000000,
    typicalTerm: '5/1, 7/1, 10/1 ARM',
    rates: '5.5% - 6.5%',
    bestFor: [
      'Short-term homeowners',
      'Lower initial payments',
      'Expecting income increase',
      'Refinancing before adjustment',
    ],
    requirements: ['Ability to handle payment increases', 'Understanding of rate caps'],
    color: '#FFD400',
  },
  {
    id: 'interest-only',
    name: 'Interest-Only Mortgage',
    description: 'Pay only interest for initial period, then principal and interest',
    minAmount: 100000,
    maxAmount: 3000000,
    typicalTerm: '5-10 years interest-only',
    rates: '7.0% - 8.5%',
    bestFor: [
      'High-income borrowers',
      'Investment properties',
      'Maximizing cash flow initially',
      'Expecting large income increase',
    ],
    requirements: ['Excellent credit', 'Substantial down payment', 'Documented repayment plan'],
    color: '#F4212E',
  },
];

export const autoLoanTypes: LoanTypeDetail[] = [
  {
    id: 'new-car',
    name: 'New Car Loan',
    description: 'Financing for brand new vehicles with lower rates and better terms',
    minAmount: 5000,
    maxAmount: 250000,
    typicalTerm: '24-72 months',
    rates: '5.0% - 9.0%',
    bestFor: [
      'Latest models with warranty',
      'Lower interest rates',
      'Longer loan terms available',
      'Manufacturer incentives',
    ],
    requirements: ['Credit score 600+', 'Proof of income', 'Down payment recommended'],
    color: '#1D9BF0',
  },
  {
    id: 'used-car',
    name: 'Used Car Loan',
    description: 'Financing for pre-owned vehicles, flexible options for various budgets',
    minAmount: 3000,
    maxAmount: 250000,
    typicalTerm: '24-60 months',
    rates: '6.0% - 12.0%',
    bestFor: [
      'Certified pre-owned vehicles',
      'Budget-friendly options',
      'Lower depreciation',
      'Flexible credit requirements',
    ],
    requirements: ['Vehicle age restrictions', 'Mileage limits', 'Vehicle inspection'],
    color: '#00D66F',
  },
  {
    id: 'refinance-auto',
    name: 'Auto Refinance',
    description: 'Refinance existing car loan to lower rate or reduce monthly payments',
    minAmount: 5000,
    maxAmount: 250000,
    typicalTerm: '24-72 months',
    rates: '5.0% - 8.0%',
    bestFor: [
      'Lower interest rates',
      'Reduce monthly payments',
      'Improved credit score',
      'Cash-out options',
    ],
    requirements: ['Existing auto loan', 'Vehicle equity', 'Current on payments'],
    color: '#FFD400',
  },
  {
    id: 'lease-buyout',
    name: 'Lease Buyout Loan',
    description: 'Finance the purchase of your leased vehicle at lease end',
    minAmount: 10000,
    maxAmount: 250000,
    typicalTerm: '24-60 months',
    rates: '5.5% - 9.0%',
    bestFor: [
      'Purchasing leased vehicle',
      'Known vehicle history',
      'Avoiding lease penalties',
      'Flexible ownership options',
    ],
    requirements: ['Active lease', 'Buyout quote', 'Creditworthiness'],
    color: '#9E5AF2',
  },
  {
    id: 'classic-car',
    name: 'Classic/Collector Car Loan',
    description: 'Specialized financing for vintage, classic, and collector vehicles',
    minAmount: 15000,
    maxAmount: 500000,
    typicalTerm: '36-72 months',
    rates: '6.0% - 10.0%',
    bestFor: [
      'Vehicles 20+ years old',
      'Collector and exotic cars',
      'Investment vehicles',
      'Restoration projects',
    ],
    requirements: ['Vehicle appraisal', 'Collector car insurance', 'Garage storage'],
    color: '#F4212E',
  },
  {
    id: 'electric-vehicle',
    name: 'Electric Vehicle Loan',
    description: 'Specialized financing for new and used electric vehicles with incentives',
    minAmount: 15000,
    maxAmount: 200000,
    typicalTerm: '36-72 months',
    rates: '4.5% - 8.0%',
    bestFor: [
      'EVs and plug-in hybrids',
      'Federal tax credits',
      'State incentives',
      'Lower operating costs',
    ],
    requirements: ['EV-eligible vehicle', 'Home charging capability', 'Standard credit requirements'],
    color: '#00B85D',
  },
  {
    id: 'commercial-auto',
    name: 'Commercial Auto Loan',
    description: 'Financing for business vehicles, trucks, and fleet purchases',
    minAmount: 10000,
    maxAmount: 500000,
    typicalTerm: '24-60 months',
    rates: '6.0% - 10.0%',
    bestFor: [
      'Business use vehicles',
      'Fleet purchases',
      'Tax deductions',
      'Commercial trucks/vans',
    ],
    requirements: ['Business documentation', 'Commercial insurance', 'Business credit history'],
    color: '#1D9BF0',
  },
];

export const personalLoanTypes: LoanTypeDetail[] = [
  {
    id: 'debt-consolidation',
    name: 'Debt Consolidation Loan',
    description: 'Combine multiple debts into one loan with lower interest rate',
    minAmount: 1000,
    maxAmount: 100000,
    typicalTerm: '24-60 months',
    rates: '8.0% - 15.0%',
    bestFor: [
      'High-interest credit cards',
      'Multiple loan payments',
      'Simplify finances',
      'Lower total interest',
    ],
    requirements: ['Good to excellent credit', 'Stable income', 'Debt-to-income ratio'],
    color: '#1D9BF0',
  },
  {
    id: 'home-improvement',
    name: 'Home Improvement Loan',
    description: 'Unsecured loan for renovations, repairs, and home upgrades',
    minAmount: 2000,
    maxAmount: 100000,
    typicalTerm: '12-72 months',
    rates: '7.0% - 14.0%',
    bestFor: [
      'Kitchen/bathroom remodels',
      'Roof replacement',
      'HVAC systems',
      'No home equity required',
    ],
    requirements: ['Homeownership preferred', 'Renovation plan', 'Contractor estimates'],
    color: '#00D66F',
  },
  {
    id: 'medical-financing',
    name: 'Medical/Healthcare Loan',
    description: 'Finance medical procedures, dental work, or healthcare expenses',
    minAmount: 1000,
    maxAmount: 50000,
    typicalTerm: '12-60 months',
    rates: '6.0% - 12.0%',
    bestFor: [
      'Medical procedures',
      'Dental treatments',
      'Veterinary care',
      'No insurance coverage',
    ],
    requirements: ['Medical documentation', 'Credit approval', 'Income verification'],
    color: '#F4212E',
  },
  {
    id: 'wedding-loan',
    name: 'Wedding Loan',
    description: 'Finance your special day with flexible repayment options',
    minAmount: 1000,
    maxAmount: 50000,
    typicalTerm: '12-60 months',
    rates: '8.0% - 15.0%',
    bestFor: [
      'Wedding ceremonies',
      'Reception venues',
      'Honeymoon travel',
      'Wedding services',
    ],
    requirements: ['Credit check', 'Wedding planning documentation', 'Income verification'],
    color: '#FFD400',
  },
  {
    id: 'vacation-travel',
    name: 'Vacation/Travel Loan',
    description: 'Fund your dream vacation or travel adventure',
    minAmount: 1000,
    maxAmount: 35000,
    typicalTerm: '12-48 months',
    rates: '9.0% - 16.0%',
    bestFor: [
      'Dream vacations',
      'Family trips',
      'Extended travel',
      'Special occasions',
    ],
    requirements: ['Good credit', 'Travel itinerary', 'Proof of income'],
    color: '#00B85D',
  },
  {
    id: 'emergency-loan',
    name: 'Emergency Loan',
    description: 'Quick access to funds for unexpected expenses and emergencies',
    minAmount: 500,
    maxAmount: 25000,
    typicalTerm: '6-36 months',
    rates: '10.0% - 20.0%',
    bestFor: [
      'Unexpected expenses',
      'Car repairs',
      'Home emergencies',
      'Fast approval needed',
    ],
    requirements: ['Minimal documentation', 'Active bank account', 'Income verification'],
    color: '#F4212E',
  },
  {
    id: 'moving-relocation',
    name: 'Moving/Relocation Loan',
    description: 'Cover costs of moving, deposits, and relocation expenses',
    minAmount: 1000,
    maxAmount: 35000,
    typicalTerm: '12-48 months',
    rates: '8.0% - 14.0%',
    bestFor: [
      'Job relocation',
      'Moving expenses',
      'Security deposits',
      'Temporary housing',
    ],
    requirements: ['Employment verification', 'Moving documentation', 'Credit check'],
    color: '#9E5AF2',
  },
  {
    id: 'major-purchase',
    name: 'Major Purchase Loan',
    description: 'Finance large purchases like furniture, appliances, or electronics',
    minAmount: 500,
    maxAmount: 50000,
    typicalTerm: '6-60 months',
    rates: '7.0% - 15.0%',
    bestFor: [
      'Furniture sets',
      'Appliances',
      'Electronics',
      'Home office setup',
    ],
    requirements: ['Purchase receipts', 'Credit approval', 'Income documentation'],
    color: '#1D9BF0',
  },
  {
    id: 'green-loan',
    name: 'Green/Eco Loan',
    description: 'Finance eco-friendly home improvements and sustainable upgrades',
    minAmount: 2000,
    maxAmount: 100000,
    typicalTerm: '24-72 months',
    rates: '5.0% - 9.0%',
    bestFor: [
      'Solar panel installation',
      'Energy-efficient windows',
      'Green home upgrades',
      'Lower interest rates',
    ],
    requirements: ['Energy audit', 'Contractor certification', 'Homeownership'],
    color: '#00B85D',
  },
];
