export interface BankInfo {
  name: string;
  logo: string;
  color: string;
}

export const BANKS: BankInfo[] = [
  { name: "Chase", logo: "https://cdn.brandfetch.io/chase.com/w/400/h/400", color: "#117ACA" },
  { name: "Bank of America", logo: "https://cdn.brandfetch.io/bankofamerica.com/w/400/h/400", color: "#E31837" },
  { name: "Wells Fargo", logo: "https://cdn.brandfetch.io/wellsfargo.com/w/400/h/400", color: "#D71E28" },
  { name: "Citibank", logo: "https://cdn.brandfetch.io/citi.com/w/400/h/400", color: "#056DAE" },
  { name: "PNC Bank", logo: "https://cdn.brandfetch.io/pnc.com/w/400/h/400", color: "#F47920" },
  { name: "Truist", logo: "https://cdn.brandfetch.io/truist.com/w/400/h/400", color: "#5E2B97" },
  { name: "US Bank", logo: "https://cdn.brandfetch.io/usbank.com/w/400/h/400", color: "#0A2240" },
  { name: "Capital One", logo: "https://cdn.brandfetch.io/capitalone.com/w/400/h/400", color: "#004879" },
  { name: "TD Bank", logo: "https://cdn.brandfetch.io/td.com/w/400/h/400", color: "#00A850" },
  { name: "Navy Federal", logo: "https://cdn.brandfetch.io/navyfederal.org/w/400/h/400", color: "#003366" },
  { name: "USAA", logo: "https://cdn.brandfetch.io/usaa.com/w/400/h/400", color: "#003866" },
  { name: "Ally Bank", logo: "https://cdn.brandfetch.io/ally.com/w/400/h/400", color: "#6F2C91" },
  { name: "Marcus by Goldman Sachs", logo: "https://cdn.brandfetch.io/marcus.com/w/400/h/400", color: "#1A1A1A" },
  { name: "Discover", logo: "https://cdn.brandfetch.io/discover.com/w/400/h/400", color: "#FF6000" },
  { name: "Synchrony", logo: "https://cdn.brandfetch.io/synchrony.com/w/400/h/400", color: "#FDB71A" },
  { name: "American Express", logo: "https://cdn.brandfetch.io/americanexpress.com/w/400/h/400", color: "#006FCF" },
  { name: "Regions Bank", logo: "https://cdn.brandfetch.io/regions.com/w/400/h/400", color: "#76BC21" },
  { name: "KeyBank", logo: "https://cdn.brandfetch.io/key.com/w/400/h/400", color: "#E87722" },
  { name: "Fifth Third Bank", logo: "https://cdn.brandfetch.io/53.com/w/400/h/400", color: "#0088D0" },
  { name: "BMO Harris", logo: "https://cdn.brandfetch.io/bmo.com/w/400/h/400", color: "#0075C9" },
  { name: "Huntington Bank", logo: "https://cdn.brandfetch.io/huntington.com/w/400/h/400", color: "#68BC34" },
  { name: "Citizens Bank", logo: "https://cdn.brandfetch.io/citizensbank.com/w/400/h/400", color: "#004B8D" },
  { name: "M&T Bank", logo: "https://cdn.brandfetch.io/mtb.com/w/400/h/400", color: "#00A758" },
  { name: "Santander", logo: "https://cdn.brandfetch.io/santanderbank.com/w/400/h/400", color: "#EC0000" },
  { name: "SoFi", logo: "https://cdn.brandfetch.io/sofi.com/w/400/h/400", color: "#8C1D40" },
  { name: "Chime", logo: "https://cdn.brandfetch.io/chime.com/w/400/h/400", color: "#2DB883" },
  { name: "Varo", logo: "https://cdn.brandfetch.io/varomoney.com/w/400/h/400", color: "#FF6B35" },
  { name: "Affirm", logo: "https://cdn.brandfetch.io/affirm.com/w/400/h/400", color: "#24BFBF" },
  { name: "Afterpay", logo: "https://cdn.brandfetch.io/afterpay.com/w/400/h/400", color: "#B2FCE4" },
  { name: "Klarna", logo: "https://cdn.brandfetch.io/klarna.com/w/400/h/400", color: "#FFB3C7" },
  { name: "Rocket Mortgage", logo: "https://cdn.brandfetch.io/rocketmortgage.com/w/400/h/400", color: "#005DAA" },
  { name: "Better.com", logo: "https://cdn.brandfetch.io/better.com/w/400/h/400", color: "#01D88D" },
  { name: "Quicken Loans", logo: "https://cdn.brandfetch.io/quickenloans.com/w/400/h/400", color: "#005DAA" },
  { name: "loanDepot", logo: "https://cdn.brandfetch.io/loandepot.com/w/400/h/400", color: "#FF6B35" },
  { name: "Guaranteed Rate", logo: "https://cdn.brandfetch.io/rate.com/w/400/h/400", color: "#E31837" },
  { name: "Caliber Home Loans", logo: "https://cdn.brandfetch.io/caliberhomeloans.com/w/400/h/400", color: "#003366" },
  { name: "Fairway Independent", logo: "https://cdn.brandfetch.io/fairwayindependentmc.com/w/400/h/400", color: "#D71E28" },
  { name: "New American Funding", logo: "https://cdn.brandfetch.io/newamericanfunding.com/w/400/h/400", color: "#FF9F0A" },
  { name: "LoanPal", logo: "https://cdn.brandfetch.io/loanpal.com/w/400/h/400", color: "#0088D0" },
  { name: "LendingTree", logo: "https://cdn.brandfetch.io/lendingtree.com/w/400/h/400", color: "#76BC21" },
  { name: "Freedom Mortgage", logo: "https://cdn.brandfetch.io/freedommortgage.com/w/400/h/400", color: "#E87722" },
];
